### ISSUE TITLE
Doesn't connect to Holochain for me

### ISSUE THREAD

**Issue by marcusnewton** [kristoferlund/holotxt#1]
I'm working on debugging this but logging it here in case I get nowhere. Everything seems to be up and running:

- `sim2h_server` on port 9000
- alice conductor on 3401
- bob conductor on 3402
- alice ui server on 3001
- bob ui server on 3002

All ports are forwarded from my Droplet. Web UIs load and they just say 'Connecting to Holochain'.

Is there a port I'm missing?

**Comment by marcusnewton** [comment]
Thought it might be my mistake. Never mind, conductor ports 3401 and 3402 werent forwarding to the same port on `localhost`.

**Comment by kristoferlund** [comment]
This was resolved, right?

**Comment by marcusnewton** [comment]
Indeed, was a problem on my end, specific to using a remote server which most users won't run into.
