### ISSUE TITLE
"create" adds entries to local source chain but they do not appear in the GUI

### ISSUE THREAD

**Issue by thedavidmeister** [kristoferlund/holotxt#2]

**Comment by kristoferlund** [comment]
Thanks for reporting. Does the problem occur every time you push "create"? 

Did you run using Holoscape? If so, what version? If not, what holochain version / nix-shell setup did you use.

**Comment by kristoferlund** [comment]
No clarification needed, thanks. The list_texts zome function doesn't play well with 0.0.42. Investigating..

**Comment by kristoferlund** [comment]
I've fixed a number of small issues now, the current version should run much more stable. I will close this issue for now, please post again if you notice other things not working.

**Comment by thedavidmeister** [comment]
@kristoferlund are there any things that could be improved upstream here?
