### ISSUE TITLE
Disappearance of text

### ISSUE THREAD

**Issue by iPlumb3r** [kristoferlund/holotxt#5]
10 days ago I create 2 texts with holo.txt 
Text addresses :
   - Distributed Web : QmfK24gQ87151BAn7stVC1eGEm8A7k7p8wiGYfLH5Gpe7v 
   - Semantic Technologies : QmWbp3f2YfuCevtVPmPQgU2WN9eRxvHnVeP3HDa7wJKanY

Just open holo.txt today : the text was not here anymore !
I mean they are not visibles "by default" from my user

**Comment by kristoferlund** [comment]
Issues should be solved in latest release. Cheers // Kristofer
